version: '3.0'

services:
  grafana:
    container_name: 'mpco-mpcoform-panel'
    build:
      context: ./.config
      args:
        grafana_version: ${GRAFANA_VERSION:-9.2.5}
    ports:
      - 3000:3000/tcp
    networks:
      - peresvet
    volumes:
      - ./dist:/var/lib/grafana/plugins/mpco-mpcoform-panel
      - ./provisioning:/etc/grafana/provisioning
networks:
  peresvet:
    name: compose_default
    external: true
